<a href="https://colab.research.google.com/github/HarshKumarChoudary/Data-Mining/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

nutrients = pd.read_csv('/content/nutrients_csvfile.csv')
nutrients.head()
nutrients=nutrients.replace("t",np.nan)
nutrients=nutrients.replace("t'",np.nan)
nutrients=nutrients.replace(",",np.nan, regex=True)
nutrients['Fiber']=nutrients['Fiber'].replace("a",np.nan, regex=True)
nutrients['Calories'][91]=(8+44)/2

nutrients['Grams']=pd.to_numeric(nutrients['Grams'])
nutrients['Calories']=pd.to_numeric(nutrients['Calories'])
nutrients['Protein']=pd.to_numeric(nutrients['Protein'])
nutrients['Fat']=pd.to_numeric(nutrients['Fat'])
nutrients['Sat.Fat']=pd.to_numeric(nutrients['Sat.Fat'])
nutrients['Fiber']=pd.to_numeric(nutrients['Fiber'])
nutrients['Carbs']=pd.to_numeric(nutrients['Carbs'])

nutrients = nutrients.drop('Category',1)
nutrients = nutrients.drop('Measure',1)
nutrients = nutrients.drop('Food',1)

# X = nutrients.iloc[:,:].values
# Y = nutrients.iloc[:,1].values
# X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

# print(X)

x = nutrients[['Grams','Calories','Protein','Fat','Sat.Fat','Fiber','Carbs']]
y = nutrients[['Protein']]

print(Y)

[660. 360. 127. 345.  nan 515. 290. 290. 165. 690. 235. 128. 275. 285.
 300. 275. 170. 430. 240. 195.  70. 226. 105. 105. 105. 105. 150. 220.
 120. 100. 113. 113. 665. 992. 806. 100. 110. 125. 125. 125.  60.  75.
 470.  95. 245. 245. 185. 390. 330. 220. 185. 120. 115. 480. 185. 185.
 245. 290. 140. 370. 480. 314. 285. 260. 290. 170. 165. 310. 475. 265.
 185. 305.  87. 170.  90. 200. 200. 135. 182. 211.  92. 155. 231. 125.
 120. 180. 104. 170. 110. 180. 170.  26.  18.  25. 140. 260. 250. 230.
  17.  27.   1.  45.  60.  32.  40.  45.  45.  20.  30.  20.   5.  30.
  51.  92. 170.   6.  80.  30.  10.  45.  40.  48. 212.  14.  13.  12.
  30.  32.  80.  22.   2.  95.  66.  70.  nan 115.  53.  10.  25. 255.
 100. 155. 230. 268. 145.  80. 110.  10.  32. 260.  26.  35.  95. 155.
 235.  50.  30.  50.  15.  45.  40.   9. 125.  14.  70. 100. 220. 220.
  55. 140. 185.  85.  85. 245.  40. 100.  65. 530. 505. 120.  90. 130.
 195. 170.  50. 100.  70. 100. 160.  30. 430. 405.  72. 105.  60. 112.
 330. 

In [ ]:
X = nutrients.iloc[:,:].values
Y = nutrients.iloc[:,1].values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)


In [ ]:
print(X_train)

[[5.00e+01 2.00e+01      nan ... 0.00e+00 5.00e-01 5.00e+00]
 [8.50e+01 1.35e+02 1.60e+01 ... 4.00e+00 0.00e+00 6.00e+00]
 [1.40e+01 1.00e+02      nan ... 9.00e+00 0.00e+00      nan]
 ...
 [1.20e+02 3.90e+02 1.30e+01 ... 0.00e+00 2.80e+00 7.90e+01]
 [2.80e+01 1.05e+02 7.00e+00 ... 7.00e+00 0.00e+00      nan]
 [5.00e+01 1.70e+01 1.00e+00 ... 0.00e+00 3.00e-01 3.00e+00]]


In [ ]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors=5,add_indicator=True)
knn.fit(X_train)

# from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn import metrics
# x_train, x_test, y_train, y_test = train_test_split(x,y,random_state =5)
# knnclassifier = KNeighborsClassifier(n_neighbors=5)
# knnclassifier.fit(x_train,y_train)
# y_pred = knnclassifier.predict(x_test)
# metrics.accuracy_score(y_test,y_pred)

KNNImputer(add_indicator=True, copy=True, metric='nan_euclidean',
           missing_values=nan, n_neighbors=5, weights='uniform')

In [ ]:
X_train = knn.transform(X_train)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(X_train)

[[ 5.000e+01  2.000e+01  8.000e-01  2.000e-01  0.000e+00  5.000e-01
   5.000e+00  0.000e+00  0.000e+00  1.000e+00  1.000e+00  0.000e+00
   0.000e+00  0.000e+00]
 [ 8.500e+01  1.350e+02  1.600e+01  5.000e+00  4.000e+00  0.000e+00
   6.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00]
 [ 1.400e+01  1.000e+02  5.000e+00  1.100e+01  9.000e+00  0.000e+00
   1.520e+01  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00
   0.000e+00  1.000e+00]
 [ 3.000e+01  9.800e+01  1.000e+00  0.000e+00  0.000e+00  0.000e+00
   2.300e+01  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00]
 [ 2.460e+02  1.270e+02  9.000e+00  5.000e+00  4.000e+00  0.000e+00
   1.300e+01  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00]
 [ 1.000e+02  2.600e+01  3.000e+00  4.000e-01  0.000e+00  1.000e+00
   3.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00
   0.000e+00  0.000e+00]
 [ 8.500e+01  1.200e+02  1.700e+01

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn import metrics
# x_train, x_test, y_train, y_test = train_test_split(x,y,random_state =5)
# knnclassifier = KNeighborsClassifier(n_neighbors=5)
# knnclassifier.fit(x_train,y_train)
# y_pred = knnclassifier.predict(x_test)
# metrics.accuracy_score(y_test,y_pred)
# to change use .astype() 


NameError: ignored

In [ ]:
# from sklearn.model_selection import cross_val_score
# knnclassifier = KNeighborsClassifier(n_neighbors=4)
# print(cross_val_score(knnclassifier, X, Y, cv=10, scoring ='accuracy').mean())

for val in X:
  print(val)

[976. 660.  32.  40.  36.   0.  48.]
[984. 360.  36.  nan  nan   0.  52.]
[246. 127.   9.   5.   4.   0.  13.]
[252. 345.  16.  20.  18.   0.  24.]
[  nan   nan  89.   42.   23.    1.4 119. ]
[103. 515.  27.  28.  24.   0.  39.]
[ 85. 290.  30.  nan  nan   0.  42.]
[ 85. 290.  30.  nan  nan   1.  42.]
[244. 165.   8.  10.   8.   0.  11.]
[540. 690.  24.  24.  22.   0.  70.]
[252. 235.   8.  11.  10.   0.  26.]
[250. 128.  18.   4.   3.   1.  13.]
[248. 275.   9.  10.   9.   0.  40.]
[248. 285.  13.  14.  11.   0.  28.]
[188. 300.   6.  18.  16.   0.  29.]
[190. 275.   9.  10.   9.   0.  32.]
[120. 170.   4.  15.  13.   0.   5.]
[119. 430.   2.  44.  27.   1.   3.]
[225. 240.  30.  11.  10.   0.   6.]
[225. 195.  38.  nan  nan   0.   6.]
[17. 70.  4.  6.  5.  0. nan]
[ 56. 226.  14.  19.  17.   0.   1.]
[ 28. 105.   2.  11.  10.   0.   1.]
[ 28. 105.   7.   9.   8.   0.  nan]
[ 28. 105.   6.   9.   8.   0.  nan]
[ 28. 105.   7.   8.   7.   0.  nan]
[100. 150.  12.  12.  10.   0.  nan]
[

In [ ]:
#New starting 
import numpy as np
import pandas as pd

nutrient = pd.read_csv('/content/nutrients_csvfile.csv')
nutrient.head()
nutrient=nutrient.replace("t",np.nan)
nutrient=nutrient.replace("t'",np.nan)
nutrient=nutrient.replace(",",np.nan, regex=True)
nutrient['Fiber']=nutrient['Fiber'].replace("a",np.nan, regex=True)
nutrient['Calories'][91]=(8+44)/2

nutrient['Grams']=pd.to_numeric(nutrient['Grams'])
nutrient['Calories']=pd.to_numeric(nutrient['Calories'])
nutrient['Protein']=pd.to_numeric(nutrient['Protein'])
nutrient['Fat']=pd.to_numeric(nutrient['Fat'])
nutrient['Sat.Fat']=pd.to_numeric(nutrient['Sat.Fat'])
nutrient['Fiber']=pd.to_numeric(nutrient['Fiber'])
nutrient['Carbs']=pd.to_numeric(nutrient['Carbs'])

nutrient = nutrient.drop('Category',1)
nutrient = nutrient.drop('Measure',1)
nutrient = nutrient.drop('Food',1)

# X = nutrients.iloc[:,:].values
# Y = nutrients.iloc[:,1].values
# X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

# print(X)
for col in nutrient.columns:
  nutrient[col] = nutrient[col].astype(float)


x = nutrient[['Grams','Calories','Protein','Fat','Sat.Fat','Fiber','Carbs']]
y = nutrient[['Protein']]

print(X)

[[ 9.76e+02  6.60e+02  3.20e+01  4.00e+01  3.60e+01  0.00e+00  4.80e+01]
 [ 9.84e+02  3.60e+02  3.60e+01       nan       nan  0.00e+00  5.20e+01]
 [ 2.46e+02  1.27e+02  9.00e+00  5.00e+00  4.00e+00  0.00e+00  1.30e+01]
 [ 2.52e+02  3.45e+02  1.60e+01  2.00e+01  1.80e+01  0.00e+00  2.40e+01]
 [      nan       nan  8.90e+01  4.20e+01  2.30e+01  1.40e+00  1.19e+02]
 [ 1.03e+02  5.15e+02  2.70e+01  2.80e+01  2.40e+01  0.00e+00  3.90e+01]
 [ 8.50e+01  2.90e+02  3.00e+01       nan       nan  0.00e+00  4.20e+01]
 [ 8.50e+01  2.90e+02  3.00e+01       nan       nan  1.00e+00  4.20e+01]
 [ 2.44e+02  1.65e+02  8.00e+00  1.00e+01  8.00e+00  0.00e+00  1.10e+01]
 [ 5.40e+02  6.90e+02  2.40e+01  2.40e+01  2.20e+01  0.00e+00  7.00e+01]
 [ 2.52e+02  2.35e+02  8.00e+00  1.10e+01  1.00e+01  0.00e+00  2.60e+01]
 [ 2.50e+02  1.28e+02  1.80e+01  4.00e+00  3.00e+00  1.00e+00  1.30e+01]
 [ 2.48e+02  2.75e+02  9.00e+00  1.00e+01  9.00e+00  0.00e+00  4.00e+01]
 [ 2.48e+02  2.85e+02  1.30e+01  1.40e+01  1.10e+01

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state =5)
knnclassifier = KNeighborsClassifier(n_neighbors=5)
knnclassifier.fit(x_train,y_train,add_indicator=True)
y_pred = knnclassifier.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

TypeError: ignored

In [ ]:
https://github.com/krishnaik06/model_selections/blob/master/Purchased_Dataset.csv


use the above link to see how classifier works and also note that i tried it but i am not getting the results 
reason for that is that classifiers are only working for transformed datasets i.e. the datasets whose nan is removed and is now pure to check its accuracy