<a href="https://colab.research.google.com/github/HarshKumarChoudary/Data-Mining/blob/main/Machine_Learning_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 
import plotly.express as px
import seaborn as sns
import plotly.offline as py
import plotly.graph_objects as go

In [ ]:
nutrients=pd.read_csv("/content/nutrients_csvfile.csv")
nutrients.head()

Food Measure  Grams  ... Fiber Carbs        Category
0             Cows' milk   1 qt.    976  ...     0    48  Dairy products
1              Milk skim   1 qt.    984  ...     0    52  Dairy products
2             Buttermilk   1 cup    246  ...     0    13  Dairy products
3  Evaporated, undiluted   1 cup    252  ...     0    24  Dairy products
4         Fortified milk  6 cups  1,419  ...   1.4   119  Dairy products

[5 rows x 10 columns]

In [ ]:
nutrients=nutrients.replace("t",-1)
nutrients=nutrients.replace("t'",-1)

nutrients.head()

Food Measure  Grams  ... Fiber Carbs        Category
0             Cows' milk   1 qt.    976  ...     0    48  Dairy products
1              Milk skim   1 qt.    984  ...     0    52  Dairy products
2             Buttermilk   1 cup    246  ...     0    13  Dairy products
3  Evaporated, undiluted   1 cup    252  ...     0    24  Dairy products
4         Fortified milk  6 cups  1,419  ...   1.4   119  Dairy products

[5 rows x 10 columns]

In [ ]:
nutrients.isna().sum()

Food        0
Measure     0
Grams       0
Calories    1
Protein     0
Fat         0
Sat.Fat     2
Fiber       0
Carbs       0
Category    0
dtype: int64

In [ ]:
nutrients=nutrients.replace(",","", regex=True)
nutrients['Fiber']=nutrients['Fiber'].replace("a","", regex=True)
nutrients['Calories'][91]=(8+44)/2


In [ ]:
nutrients.head()

Food Measure Grams  ... Fiber Carbs        Category
0            Cows' milk   1 qt.   976  ...     0    48  Dairy products
1             Milk skim   1 qt.   984  ...     0    52  Dairy products
2            Buttermilk   1 cup   246  ...     0    13  Dairy products
3  Evaporated undiluted   1 cup   252  ...     0    24  Dairy products
4        Fortified milk  6 cups  1419  ...   1.4   119  Dairy products

[5 rows x 10 columns]

In [ ]:
nutrients['Grams']=pd.to_numeric(nutrients['Grams'])
nutrients['Calories']=pd.to_numeric(nutrients['Calories'])
nutrients['Protein']=pd.to_numeric(nutrients['Protein'])
nutrients['Fat']=pd.to_numeric(nutrients['Fat'])
nutrients['Sat.Fat']=pd.to_numeric(nutrients['Sat.Fat'])
nutrients['Fiber']=pd.to_numeric(nutrients['Fiber'])
nutrients['Carbs']=pd.to_numeric(nutrients['Carbs'])

In [ ]:
nutrients.head()

Food Measure  Grams  ...  Fiber  Carbs        Category
0            Cows' milk   1 qt.    976  ...    0.0   48.0  Dairy products
1             Milk skim   1 qt.    984  ...    0.0   52.0  Dairy products
2            Buttermilk   1 cup    246  ...    0.0   13.0  Dairy products
3  Evaporated undiluted   1 cup    252  ...    0.0   24.0  Dairy products
4        Fortified milk  6 cups   1419  ...    1.4  119.0  Dairy products

[5 rows x 10 columns]

In [ ]:
nutrients.dtypes

Food         object
Measure      object
Grams         int64
Calories    float64
Protein       int64
Fat           int64
Sat.Fat     float64
Fiber       float64
Carbs       float64
Category     object
dtype: object

In [ ]:
nutrients.describe()

Grams     Calories     Protein  ...     Sat.Fat       Fiber       Carbs
count   335.000000   334.000000  335.000000  ...  333.000000  334.000000  335.000000
mean    143.211940   188.802395    8.573134  ...    6.438438    2.376078   24.982388
std     138.668626   184.453018   17.733722  ...   18.517656   16.078272   35.833106
min      11.000000     0.000000   -1.000000  ...    0.000000    0.000000    0.000000
25%      60.000000    75.000000    1.000000  ...    0.000000    0.000000    3.000000
50%     108.000000   131.000000    3.000000  ...    0.000000    0.200000   14.000000
75%     200.000000   250.000000   12.000000  ...    8.000000    1.000000   30.500000
max    1419.000000  1373.000000  232.000000  ...  234.000000  235.000000  236.000000

[8 rows x 7 columns]

In [ ]:
np.random.seed(seed=0)
h = np.random.choice(a=nutrients.index,replace=False,size=20)
nutrients.loc[h,'Grams']=np.nan

In [ ]:
nutrients.isna().sum()

Food         0
Measure      0
Grams       20
Calories     1
Protein      0
Fat          0
Sat.Fat      2
Fiber        1
Carbs        0
Category     0
dtype: int64

In [ ]:
nutrients.drop('Category',1)
nutrients.drop('Measure',1)

Food   Grams  ...  Carbs                 Category
0              Cows' milk   976.0  ...   48.0           Dairy products
1               Milk skim   984.0  ...   52.0           Dairy products
2              Buttermilk   246.0  ...   13.0           Dairy products
3    Evaporated undiluted   252.0  ...   24.0           Dairy products
4          Fortified milk  1419.0  ...  119.0           Dairy products
..                    ...     ...  ...    ...                      ...
330   Fruit-flavored soda   346.0  ...   42.0  DrinksAlcohol Beverages
331            Ginger ale   346.0  ...   28.0  DrinksAlcohol Beverages
332             Root beer   346.0  ...   35.0  DrinksAlcohol Beverages
333                Coffee   230.0  ...    1.0  DrinksAlcohol Beverages
334                   Tea   230.0  ...    1.0  DrinksAlcohol Beverages

[335 rows x 9 columns]

In [ ]:
nutrients = nutrients.drop('Category',1)
nutrients = nutrients.drop('Measure',1)

In [ ]:
nutrients.head()
nutrients.describe()
nutrients.isna().sum()

Grams       20
Calories     1
Protein      0
Fat          0
Sat.Fat      2
Fiber        1
Carbs        0
dtype: int64

In [ ]:
X = nutrients.iloc[:,:].values
Y = nutrients.iloc[:,1].values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [ ]:
print(X_train)

[[5.60e+01 2.26e+02 1.40e+01 ... 1.70e+01 0.00e+00 1.00e+00]
 [1.00e+02 1.30e+01 0.00e+00 ... 0.00e+00 5.00e-01 3.00e+00]
 [8.50e+01 1.35e+02 1.60e+01 ... 4.00e+00 0.00e+00 6.00e+00]
 ...
 [2.20e+02 8.15e+02 0.00e+00 ... 0.00e+00 0.00e+00 2.10e+02]
 [5.20e+01 3.43e+02 5.00e+00 ... 2.50e+01 1.10e+00 7.00e+00]
 [2.85e+02 5.00e+01 1.00e+00 ... 0.00e+00 1.00e+00 1.40e+01]]


In [ ]:
nutrients.head()

Grams  Calories  Protein  Fat  Sat.Fat  Fiber  Carbs
0   976.0     660.0       32   40     36.0    0.0   48.0
1   984.0     360.0       36    0      0.0    0.0   52.0
2   246.0     127.0        9    5      4.0    0.0   13.0
3   252.0     345.0       16   20     18.0    0.0   24.0
4  1419.0    1373.0       89   42     23.0    1.4  119.0

In [ ]:
array_sum = np. sum(X_train)
array_has_nan = np. isnan(array_sum)
print(array_has_nan)

True


In [ ]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=5,add_indicator=True)

In [ ]:
num = [col for col in X_train.columns if X_train[col].dtypes=='o']
X_train[num]

SyntaxError: ignored

In [ ]:
knn.fit(X_train)

KNNImputer(add_indicator=True, copy=True, metric='nan_euclidean',
           missing_values=nan, n_neighbors=5, weights='uniform')

In [ ]:
pd.DataFrame(knn.transform(X_train)).isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [ ]:
knn.transform(X_train)

array([[ 56., 226.,  14., ...,   0.,   0.,   0.],
       [100.,  13.,   0., ...,   0.,   0.,   0.],
       [ 85., 135.,  16., ...,   0.,   0.,   0.],
       ...,
       [220., 815.,   0., ...,   0.,   0.,   0.],
       [ 52., 343.,   5., ...,   0.,   0.,   0.],
       [285.,  50.,   1., ...,   0.,   0.,   0.]])

In [ ]:
pd.DataFrame(knn.transform(X_train))
pd.DataFrame(knn.transform(X_train)).isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [ ]:
#call same function for X_test also
import sys
np.set_printoptions(threshold=sys.maxsize)
print(X_train)

[[ 5.600e+01  2.260e+02  1.400e+01  1.900e+01  1.700e+01  0.000e+00
   1.000e+00]
 [ 1.000e+02  1.300e+01  0.000e+00  0.000e+00  0.000e+00  5.000e-01
   3.000e+00]
 [ 8.500e+01  1.350e+02  1.600e+01  5.000e+00  4.000e+00  0.000e+00
   6.000e+00]
 [ 2.000e+01  5.000e+01  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   1.300e+01]
 [ 6.500e+01  1.050e+02  1.000e+00  1.300e+01  1.200e+01  1.000e+00
   1.000e+00]
 [ 3.460e+02  1.400e+02  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   3.500e+01]
 [ 2.800e+01  1.050e+02  7.000e+00  9.000e+00  8.000e+00  0.000e+00
   0.000e+00]
 [ 1.650e+02  1.000e+00  1.200e+01  0.000e+00        nan  0.000e+00
   8.000e-01]
 [ 2.450e+02  1.750e+02  6.000e+00  7.000e+00  6.000e+00  5.000e-01
   2.200e+01]
 [ 2.480e+02  2.850e+02  1.300e+01  1.400e+01  1.100e+01  0.000e+00
   2.800e+01]
 [ 4.000e+01  1.100e+02  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   2.900e+01]
 [ 2.800e+01  1.050e+02  6.000e+00  9.000e+00  8.000e+00  0.000e+00
   0.000e+00]
 [ 7.500e+01  2.

In [ ]:
X_train = knn.transform(X_train)

np.set_printoptions(threshold=sys.maxsize)
print(X_train)

[[ 5.600e+01  2.260e+02  1.400e+01  1.900e+01  1.700e+01  0.000e+00
   1.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 1.000e+02  1.300e+01  0.000e+00  0.000e+00  0.000e+00  5.000e-01
   3.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 8.500e+01  1.350e+02  1.600e+01  5.000e+00  4.000e+00  0.000e+00
   6.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 2.000e+01  5.000e+01  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   1.300e+01  0.000e+00  0.000e+00  0.000e+00]
 [ 6.500e+01  1.050e+02  1.000e+00  1.300e+01  1.200e+01  1.000e+00
   1.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 3.460e+02  1.400e+02  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   3.500e+01  0.000e+00  0.000e+00  0.000e+00]
 [ 2.800e+01  1.050e+02  7.000e+00  9.000e+00  8.000e+00  0.000e+00
   0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 1.650e+02  1.000e+00  1.200e+01  0.000e+00  0.000e+00  0.000e+00
   8.000e-01  0.000e+00  1.000e+00  0.000e+00]
 [ 2.450e+02  1.750e+02  6.000e+00  7.000e+00  6.000e+00  5.000e-01
   2.200e+01